//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.VirtualRobotControl
{
    [Serializable]
    public class AuboJointsStateMsg : Message
    {
        public const string k_RosMessageName = "virtual_robot_control/AuboJointsState";
        public override string RosMessageName => k_RosMessageName;

        public double[] joints;
        public Geometry.PoseMsg pose;
        public Geometry.PoseMsg transform;

        public AuboJointsStateMsg()
        {
            this.joints = new double[6];
            this.pose = new Geometry.PoseMsg();
            this.transform = new Geometry.PoseMsg();
        }

        public AuboJointsStateMsg(double[] joints, Geometry.PoseMsg pose, Geometry.PoseMsg transform)
        {
            this.joints = joints;
            this.pose = pose;
            this.transform = transform;
        }

        public static AuboJointsStateMsg Deserialize(MessageDeserializer deserializer) => new AuboJointsStateMsg(deserializer);

        private AuboJointsStateMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.joints, sizeof(double), 6);
            this.pose = Geometry.PoseMsg.Deserialize(deserializer);
            this.transform = Geometry.PoseMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.joints);
            serializer.Write(this.pose);
            serializer.Write(this.transform);
        }

        public override string ToString()
        {
            return "AuboJointsStateMsg: " +
            "\njoints: " + System.String.Join(", ", joints.ToList()) +
            "\npose: " + pose.ToString() +
            "\ntransform: " + transform.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
