//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.VirtualRobotControl
{
    [Serializable]
    public class VirtualJointPosMsg : Message
    {
        public const string k_RosMessageName = "virtual_robot_control/VirtualJointPos";
        public override string RosMessageName => k_RosMessageName;

        public float joint1;
        public float joint2;
        public float joint3;
        public float joint4;
        public float joint5;
        public float joint6;

        public VirtualJointPosMsg()
        {
            this.joint1 = 0.0f;
            this.joint2 = 0.0f;
            this.joint3 = 0.0f;
            this.joint4 = 0.0f;
            this.joint5 = 0.0f;
            this.joint6 = 0.0f;
        }

        public VirtualJointPosMsg(float joint1, float joint2, float joint3, float joint4, float joint5, float joint6)
        {
            this.joint1 = joint1;
            this.joint2 = joint2;
            this.joint3 = joint3;
            this.joint4 = joint4;
            this.joint5 = joint5;
            this.joint6 = joint6;
        }

        public static VirtualJointPosMsg Deserialize(MessageDeserializer deserializer) => new VirtualJointPosMsg(deserializer);

        private VirtualJointPosMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.joint1);
            deserializer.Read(out this.joint2);
            deserializer.Read(out this.joint3);
            deserializer.Read(out this.joint4);
            deserializer.Read(out this.joint5);
            deserializer.Read(out this.joint6);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.joint1);
            serializer.Write(this.joint2);
            serializer.Write(this.joint3);
            serializer.Write(this.joint4);
            serializer.Write(this.joint5);
            serializer.Write(this.joint6);
        }

        public override string ToString()
        {
            return "VirtualJointPosMsg: " +
            "\njoint1: " + joint1.ToString() +
            "\njoint2: " + joint2.ToString() +
            "\njoint3: " + joint3.ToString() +
            "\njoint4: " + joint4.ToString() +
            "\njoint5: " + joint5.ToString() +
            "\njoint6: " + joint6.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
