//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.VirtualRobotControl
{
    [Serializable]
    public class AuboSycServiceResponse : Message
    {
        public const string k_RosMessageName = "virtual_robot_control/AuboSycService";
        public override string RosMessageName => k_RosMessageName;

        public bool aim_get;
        public double[] aim_joints;

        public AuboSycServiceResponse()
        {
            this.aim_get = false;
            this.aim_joints = new double[6];
        }

        public AuboSycServiceResponse(bool aim_get, double[] aim_joints)
        {
            this.aim_get = aim_get;
            this.aim_joints = aim_joints;
        }

        public static AuboSycServiceResponse Deserialize(MessageDeserializer deserializer) => new AuboSycServiceResponse(deserializer);

        private AuboSycServiceResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.aim_get);
            deserializer.Read(out this.aim_joints, sizeof(double), 6);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.aim_get);
            serializer.Write(this.aim_joints);
        }

        public override string ToString()
        {
            return "AuboSycServiceResponse: " +
            "\naim_get: " + aim_get.ToString() +
            "\naim_joints: " + System.String.Join(", ", aim_joints.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
