//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.VirtualRobotControl
{
    [Serializable]
    public class AuboExecuteServiceResponse : Message
    {
        public const string k_RosMessageName = "virtual_robot_control/AuboExecuteService";
        public override string RosMessageName => k_RosMessageName;

        public bool execute;

        public AuboExecuteServiceResponse()
        {
            this.execute = false;
        }

        public AuboExecuteServiceResponse(bool execute)
        {
            this.execute = execute;
        }

        public static AuboExecuteServiceResponse Deserialize(MessageDeserializer deserializer) => new AuboExecuteServiceResponse(deserializer);

        private AuboExecuteServiceResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.execute);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.execute);
        }

        public override string ToString()
        {
            return "AuboExecuteServiceResponse: " +
            "\nexecute: " + execute.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
