//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.VirtualRobotControl
{
    [Serializable]
    public class AuboMultiPlanServiceResponse : Message
    {
        public const string k_RosMessageName = "virtual_robot_control/AuboMultiPlanService";
        public override string RosMessageName => k_RosMessageName;

        public Moveit.RobotTrajectoryMsg[] trajectories;
        public float[] total_time;

        public AuboMultiPlanServiceResponse()
        {
            this.trajectories = new Moveit.RobotTrajectoryMsg[0];
            this.total_time = new float[0];
        }

        public AuboMultiPlanServiceResponse(Moveit.RobotTrajectoryMsg[] trajectories, float[] total_time)
        {
            this.trajectories = trajectories;
            this.total_time = total_time;
        }

        public static AuboMultiPlanServiceResponse Deserialize(MessageDeserializer deserializer) => new AuboMultiPlanServiceResponse(deserializer);

        private AuboMultiPlanServiceResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.trajectories, Moveit.RobotTrajectoryMsg.Deserialize, deserializer.ReadLength());
            deserializer.Read(out this.total_time, sizeof(float), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.trajectories);
            serializer.Write(this.trajectories);
            serializer.WriteLength(this.total_time);
            serializer.Write(this.total_time);
        }

        public override string ToString()
        {
            return "AuboMultiPlanServiceResponse: " +
            "\ntrajectories: " + System.String.Join(", ", trajectories.ToList()) +
            "\ntotal_time: " + System.String.Join(", ", total_time.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
