//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.VirtualRobotControl
{
    [Serializable]
    public class AuboPlanServiceRequest : Message
    {
        public const string k_RosMessageName = "virtual_robot_control/AuboPlanService";
        public override string RosMessageName => k_RosMessageName;

        public AuboJointsMsg current_joints;
        public Geometry.PoseMsg start_pose;
        public Geometry.PoseMsg end_pose;

        public AuboPlanServiceRequest()
        {
            this.current_joints = new AuboJointsMsg();
            this.start_pose = new Geometry.PoseMsg();
            this.end_pose = new Geometry.PoseMsg();
        }

        public AuboPlanServiceRequest(AuboJointsMsg current_joints, Geometry.PoseMsg start_pose, Geometry.PoseMsg end_pose)
        {
            this.current_joints = current_joints;
            this.start_pose = start_pose;
            this.end_pose = end_pose;
        }

        public static AuboPlanServiceRequest Deserialize(MessageDeserializer deserializer) => new AuboPlanServiceRequest(deserializer);

        private AuboPlanServiceRequest(MessageDeserializer deserializer)
        {
            this.current_joints = AuboJointsMsg.Deserialize(deserializer);
            this.start_pose = Geometry.PoseMsg.Deserialize(deserializer);
            this.end_pose = Geometry.PoseMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.current_joints);
            serializer.Write(this.start_pose);
            serializer.Write(this.end_pose);
        }

        public override string ToString()
        {
            return "AuboPlanServiceRequest: " +
            "\ncurrent_joints: " + current_joints.ToString() +
            "\nstart_pose: " + start_pose.ToString() +
            "\nend_pose: " + end_pose.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
