//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.VirtualRobotControl
{
    [Serializable]
    public class AuboMultiPlanServiceRequest : Message
    {
        public const string k_RosMessageName = "virtual_robot_control/AuboMultiPlanService";
        public override string RosMessageName => k_RosMessageName;

        public AuboJointsMsg current_joints;
        public AuboPoseListMsg[] trail_list;
        public double velocity;

        public AuboMultiPlanServiceRequest()
        {
            this.current_joints = new AuboJointsMsg();
            this.trail_list = new AuboPoseListMsg[0];
            this.velocity = 0.0;
        }

        public AuboMultiPlanServiceRequest(AuboJointsMsg current_joints, AuboPoseListMsg[] trail_list, double velocity)
        {
            this.current_joints = current_joints;
            this.trail_list = trail_list;
            this.velocity = velocity;
        }

        public static AuboMultiPlanServiceRequest Deserialize(MessageDeserializer deserializer) => new AuboMultiPlanServiceRequest(deserializer);

        private AuboMultiPlanServiceRequest(MessageDeserializer deserializer)
        {
            this.current_joints = AuboJointsMsg.Deserialize(deserializer);
            deserializer.Read(out this.trail_list, AuboPoseListMsg.Deserialize, deserializer.ReadLength());
            deserializer.Read(out this.velocity);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.current_joints);
            serializer.WriteLength(this.trail_list);
            serializer.Write(this.trail_list);
            serializer.Write(this.velocity);
        }

        public override string ToString()
        {
            return "AuboMultiPlanServiceRequest: " +
            "\ncurrent_joints: " + current_joints.ToString() +
            "\ntrail_list: " + System.String.Join(", ", trail_list.ToList()) +
            "\nvelocity: " + velocity.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
