//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.PlcCommunicate
{
    [Serializable]
    public class SetPlcModeResponse : Message
    {
        public const string k_RosMessageName = "plc_communicate/SetPlcMode";
        public override string RosMessageName => k_RosMessageName;

        public bool success;

        public SetPlcModeResponse()
        {
            this.success = false;
        }

        public SetPlcModeResponse(bool success)
        {
            this.success = success;
        }

        public static SetPlcModeResponse Deserialize(MessageDeserializer deserializer) => new SetPlcModeResponse(deserializer);

        private SetPlcModeResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.success);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.success);
        }

        public override string ToString()
        {
            return "SetPlcModeResponse: " +
            "\nsuccess: " + success.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
