//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.PlcCommunicate
{
    [Serializable]
    public class SetPlcModeRequest : Message
    {
        public const string k_RosMessageName = "plc_communicate/SetPlcMode";
        public override string RosMessageName => k_RosMessageName;

        public sbyte enable;

        public SetPlcModeRequest()
        {
            this.enable = 0;
        }

        public SetPlcModeRequest(sbyte enable)
        {
            this.enable = enable;
        }

        public static SetPlcModeRequest Deserialize(MessageDeserializer deserializer) => new SetPlcModeRequest(deserializer);

        private SetPlcModeRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.enable);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.enable);
        }

        public override string ToString()
        {
            return "SetPlcModeRequest: " +
            "\nenable: " + enable.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
