//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.PlcCommunicate
{
    [Serializable]
    public class WritePlcDataRequest : Message
    {
        public const string k_RosMessageName = "plc_communicate/WritePlcData";
        public override string RosMessageName => k_RosMessageName;

        public int mode;
        public PlcWriteDataMsg write_data;

        public WritePlcDataRequest()
        {
            this.mode = 0;
            this.write_data = new PlcWriteDataMsg();
        }

        public WritePlcDataRequest(int mode, PlcWriteDataMsg write_data)
        {
            this.mode = mode;
            this.write_data = write_data;
        }

        public static WritePlcDataRequest Deserialize(MessageDeserializer deserializer) => new WritePlcDataRequest(deserializer);

        private WritePlcDataRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.mode);
            this.write_data = PlcWriteDataMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.mode);
            serializer.Write(this.write_data);
        }

        public override string ToString()
        {
            return "WritePlcDataRequest: " +
            "\nmode: " + mode.ToString() +
            "\nwrite_data: " + write_data.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
