//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.PlcCommunicate
{
    [Serializable]
    public class WritePlcDataResponse : Message
    {
        public const string k_RosMessageName = "plc_communicate/WritePlcData";
        public override string RosMessageName => k_RosMessageName;

        public bool success;
        public int error_mode;

        public WritePlcDataResponse()
        {
            this.success = false;
            this.error_mode = 0;
        }

        public WritePlcDataResponse(bool success, int error_mode)
        {
            this.success = success;
            this.error_mode = error_mode;
        }

        public static WritePlcDataResponse Deserialize(MessageDeserializer deserializer) => new WritePlcDataResponse(deserializer);

        private WritePlcDataResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.success);
            deserializer.Read(out this.error_mode);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.success);
            serializer.Write(this.error_mode);
        }

        public override string ToString()
        {
            return "WritePlcDataResponse: " +
            "\nsuccess: " + success.ToString() +
            "\nerror_mode: " + error_mode.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
