//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Hhr
{
    [Serializable]
    public class RsAlignedDepthImageRequest : Message
    {
        public const string k_RosMessageName = "hhr/RsAlignedDepthImage";
        public override string RosMessageName => k_RosMessageName;

        public string msg;

        public RsAlignedDepthImageRequest()
        {
            this.msg = "";
        }

        public RsAlignedDepthImageRequest(string msg)
        {
            this.msg = msg;
        }

        public static RsAlignedDepthImageRequest Deserialize(MessageDeserializer deserializer) => new RsAlignedDepthImageRequest(deserializer);

        private RsAlignedDepthImageRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.msg);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.msg);
        }

        public override string ToString()
        {
            return "RsAlignedDepthImageRequest: " +
            "\nmsg: " + msg.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
