//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Hhr
{
    [Serializable]
    public class RsAlignedDepthImageResponse : Message
    {
        public const string k_RosMessageName = "hhr/RsAlignedDepthImage";
        public override string RosMessageName => k_RosMessageName;

        public Sensor.ImageMsg image;

        public RsAlignedDepthImageResponse()
        {
            this.image = new Sensor.ImageMsg();
        }

        public RsAlignedDepthImageResponse(Sensor.ImageMsg image)
        {
            this.image = image;
        }

        public static RsAlignedDepthImageResponse Deserialize(MessageDeserializer deserializer) => new RsAlignedDepthImageResponse(deserializer);

        private RsAlignedDepthImageResponse(MessageDeserializer deserializer)
        {
            this.image = Sensor.ImageMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.image);
        }

        public override string ToString()
        {
            return "RsAlignedDepthImageResponse: " +
            "\nimage: " + image.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
